language: go
# For now, builds stall on latest trusty
dist: precise
go:
  - 1.8
  - tip
install:
  - go get github.com/kardianos/govendor
script:
  - govendor sync
  - make
  - make test
  - make clean
